apiVersion: v1
kind: Service
metadata:
  name: drupal-postgres
  labels:
    app: drupal
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: drupal
    tier: data
  type: ClusterIP